// Code generated by ogen, DO NOT EDIT.

package api

import (
	"net/http"

	"github.com/ogen-go/ogen/validate"
)

func decodeGetStatusResponse(resp *http.Response) (res *GetStatusOK, _ error) {
	switch resp.StatusCode {
	case 200:
		// Code 200.
		return &GetStatusOK{}, nil
	}
	return res, validate.UnexpectedStatusCodeWithResponse(resp)
}

func decodeEventWebhookResponse(resp *http.Response) (res *EventWebhookOK, _ error) {
	switch resp.StatusCode {
	case 200:
		// Code 200.
		return &EventWebhookOK{}, nil
	}
	return res, validate.UnexpectedStatusCodeWithResponse(resp)
}

func decodeSignedWebhookResponse(resp *http.Response) (res *SignedWebhookOK, _ error) {
	switch resp.StatusCode {
	case 200:
		// Code 200.
		return &SignedWebhookOK{}, nil
	}
	return res, validate.UnexpectedStatusCodeWithResponse(resp)
}
