// Code generated by ogen, DO NOT EDIT.

package api

import (
	"context"

	ht "github.com/ogen-go/ogen/http"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}

// GetStatus implements getStatus operation.
//
// GET /status
func (UnimplementedHandler) GetStatus(ctx context.Context) error {
	return ht.ErrNotImplemented
}

var _ WebhookHandler = UnimplementedHandler{}

// EventWebhook implements eventWebhook operation.
func (UnimplementedHandler) EventWebhook(ctx context.Context, req *Event) error {
	return ht.ErrNotImplemented
}

// SignedWebhook implements signedWebhook operation.
func (UnimplementedHandler) SignedWebhook(ctx context.Context, req *Event) error {
	return ht.ErrNotImplemented
}
