// Code generated by ogen, DO NOT EDIT.

package api

import (
	"context"
)

// Handler handles operations described by OpenAPI v3 specification.
type Handler interface {
	// GetStatus implements getStatus operation.
	//
	// GET /status
	GetStatus(ctx context.Context) error
}

// Server implements http server based on OpenAPI v3 specification and
// calls Handler to handle requests.
type Server struct {
	h   Handler
	sec SecurityHandler
	baseServer
}

// NewServer creates new Server.
func NewServer(h Handler, sec SecurityHandler, opts ...ServerOption) (*Server, error) {
	s, err := newServerConfig(opts...).baseServer()
	if err != nil {
		return nil, err
	}
	return &Server{
		h:          h,
		sec:        sec,
		baseServer: s,
	}, nil
}

// WebhookHandler handles webhooks described by OpenAPI v3 specification.
type WebhookHandler interface {
	// EventWebhook implements eventWebhook operation.
	//
	EventWebhook(ctx context.Context, req *Event) error
	// SignedWebhook implements signedWebhook operation.
	//
	SignedWebhook(ctx context.Context, req *Event) error
}

// WebhookServer implements http server based on OpenAPI v3 specification and
// calls WebhookHandler to handle requests.
type WebhookServer struct {
	h   WebhookHandler
	sec SecurityHandler
	baseServer
}

// NewWebhookServer creates new WebhookServer.
func NewWebhookServer(h WebhookHandler, sec SecurityHandler, opts ...ServerOption) (*WebhookServer, error) {
	s, err := newServerConfig(opts...).baseServer()
	if err != nil {
		return nil, err
	}
	return &WebhookServer{
		h:          h,
		sec:        sec,
		baseServer: s,
	}, nil
}
