// Code generated by ogen, DO NOT EDIT.

package api

import (
	"net/http"
)

// Ref: #/components/schemas/Event
type Event struct {
	ID string `json:"id"`
}

// GetID returns the value of ID.
func (s *Event) GetID() string {
	return s.ID
}

// SetID sets the value of ID.
func (s *Event) SetID(val string) {
	s.ID = val
}

// EventWebhookOK is response for EventWebhook operation.
type EventWebhookOK struct{}

// GetStatusOK is response for GetStatus operation.
type GetStatusOK struct{}

type Signature struct {
	Request *http.Request
	Roles   []string
}

// GetRequest returns the value of Request.
func (s *Signature) GetRequest() *http.Request {
	return s.Request
}

// GetRoles returns the value of Roles.
func (s *Signature) GetRoles() []string {
	return s.Roles
}

// SetRequest sets the value of Request.
func (s *Signature) SetRequest(val *http.Request) {
	s.Request = val
}

// SetRoles sets the value of Roles.
func (s *Signature) SetRoles(val []string) {
	s.Roles = val
}

// SignedWebhookOK is response for SignedWebhook operation.
type SignedWebhookOK struct{}

type TokenHeader struct {
	APIKey string
	Roles  []string
}

// GetAPIKey returns the value of APIKey.
func (s *TokenHeader) GetAPIKey() string {
	return s.APIKey
}

// GetRoles returns the value of Roles.
func (s *TokenHeader) GetRoles() []string {
	return s.Roles
}

// SetAPIKey sets the value of APIKey.
func (s *TokenHeader) SetAPIKey(val string) {
	s.APIKey = val
}

// SetRoles sets the value of Roles.
func (s *TokenHeader) SetRoles(val []string) {
	s.Roles = val
}
