// Code generated by ogen, DO NOT EDIT.

package api

import (
	"net/http"

	"go.opentelemetry.io/otel/trace"
)

func encodeGetStatusResponse(response *GetStatusOK, w http.ResponseWriter, span trace.Span) error {
	w.WriteHeader(200)

	return nil
}

func encodeEventWebhookResponse(response *EventWebhookOK, w http.ResponseWriter, span trace.Span) error {
	w.WriteHeader(200)

	return nil
}

func encodeSignedWebhookResponse(response *SignedWebhookOK, w http.ResponseWriter, span trace.Span) error {
	w.WriteHeader(200)

	return nil
}
