// Code generated by ogen, DO NOT EDIT.

package api

import (
	"context"
	"net/http"
	"strings"

	"github.com/go-faster/errors"
	"github.com/ogen-go/ogen/ogenerrors"
)

// SecurityHandler is handler for security parameters.
type SecurityHandler interface {
	// HandleSignature handles signature security.
	HandleSignature(ctx context.Context, operationName OperationName, t Signature) (context.Context, error)
	// HandleTokenHeader handles tokenHeader security.
	HandleTokenHeader(ctx context.Context, operationName OperationName, t TokenHeader) (context.Context, error)
}

func findAuthorization(h http.Header, prefix string) (string, bool) {
	v, ok := h["Authorization"]
	if !ok {
		return "", false
	}
	for _, vv := range v {
		scheme, value, ok := strings.Cut(vv, " ")
		if !ok || !strings.EqualFold(scheme, prefix) {
			continue
		}
		return value, true
	}
	return "", false
}

// operationRolesSignature is a private map storing roles per operation.
var operationRolesSignature = map[string][]string{
	SignedWebhookOperation: []string{},
}

// GetRolesForSignature returns the required roles for the given operation.
//
// This is useful for authorization scenarios where you need to know which roles
// are required for an operation.
//
// Example:
//
//	requiredRoles := GetRolesForSignature(AddPetOperation)
//
// Returns nil if the operation has no role requirements or if the operation is unknown.
func GetRolesForSignature(operation string) []string {
	roles, ok := operationRolesSignature[operation]
	if !ok {
		return nil
	}
	// Return a copy to prevent external modification
	result := make([]string, len(roles))
	copy(result, roles)
	return result
}

// operationRolesTokenHeader is a private map storing roles per operation.
var operationRolesTokenHeader = map[string][]string{
	EventWebhookOperation: []string{},
	GetStatusOperation:    []string{},
}

// GetRolesForTokenHeader returns the required roles for the given operation.
//
// This is useful for authorization scenarios where you need to know which roles
// are required for an operation.
//
// Example:
//
//	requiredRoles := GetRolesForTokenHeader(AddPetOperation)
//
// Returns nil if the operation has no role requirements or if the operation is unknown.
func GetRolesForTokenHeader(operation string) []string {
	roles, ok := operationRolesTokenHeader[operation]
	if !ok {
		return nil
	}
	// Return a copy to prevent external modification
	result := make([]string, len(roles))
	copy(result, roles)
	return result
}

func (s *Server) securitySignature(ctx context.Context, operationName OperationName, req *http.Request) (context.Context, bool, error) {
	var t Signature
	t.Request = req
	t.Roles = operationRolesSignature[operationName]
	rctx, err := s.sec.HandleSignature(ctx, operationName, t)
	if errors.Is(err, ogenerrors.ErrSkipServerSecurity) {
		return nil, false, nil
	} else if err != nil {
		return nil, false, err
	}
	return rctx, true, err
}

func (s *WebhookServer) securitySignature(ctx context.Context, operationName OperationName, req *http.Request) (context.Context, bool, error) {
	var t Signature
	t.Request = req
	t.Roles = operationRolesSignature[operationName]
	rctx, err := s.sec.HandleSignature(ctx, operationName, t)
	if errors.Is(err, ogenerrors.ErrSkipServerSecurity) {
		return nil, false, nil
	} else if err != nil {
		return nil, false, err
	}
	return rctx, true, err
}

func (s *Server) securityTokenHeader(ctx context.Context, operationName OperationName, req *http.Request) (context.Context, bool, error) {
	var t TokenHeader
	const parameterName = "X-Token"
	value := req.Header.Get(parameterName)
	if value == "" {
		return ctx, false, nil
	}
	t.APIKey = value
	t.Roles = operationRolesTokenHeader[operationName]
	rctx, err := s.sec.HandleTokenHeader(ctx, operationName, t)
	if errors.Is(err, ogenerrors.ErrSkipServerSecurity) {
		return nil, false, nil
	} else if err != nil {
		return nil, false, err
	}
	return rctx, true, err
}

func (s *WebhookServer) securityTokenHeader(ctx context.Context, operationName OperationName, req *http.Request) (context.Context, bool, error) {
	var t TokenHeader
	const parameterName = "X-Token"
	value := req.Header.Get(parameterName)
	if value == "" {
		return ctx, false, nil
	}
	t.APIKey = value
	t.Roles = operationRolesTokenHeader[operationName]
	rctx, err := s.sec.HandleTokenHeader(ctx, operationName, t)
	if errors.Is(err, ogenerrors.ErrSkipServerSecurity) {
		return nil, false, nil
	} else if err != nil {
		return nil, false, err
	}
	return rctx, true, err
}

// SecuritySource is provider of security values (tokens, passwords, etc.).
type SecuritySource interface {
	// Signature provides signature security value.
	Signature(ctx context.Context, operationName OperationName, req *http.Request) error
	// TokenHeader provides tokenHeader security value.
	TokenHeader(ctx context.Context, operationName OperationName) (TokenHeader, error)
}

func (s *Client) securitySignature(ctx context.Context, operationName OperationName, req *http.Request) error {
	if err := s.sec.Signature(ctx, operationName, req); err != nil {
		return errors.Wrap(err, "security source \"Signature\"")
	}
	return nil
}
func (s *WebhookClient) securitySignature(ctx context.Context, operationName OperationName, req *http.Request) error {
	if err := s.sec.Signature(ctx, operationName, req); err != nil {
		return errors.Wrap(err, "security source \"Signature\"")
	}
	return nil
}
func (s *Client) securityTokenHeader(ctx context.Context, operationName OperationName, req *http.Request) error {
	t, err := s.sec.TokenHeader(ctx, operationName)
	if err != nil {
		return errors.Wrap(err, "security source \"TokenHeader\"")
	}
	req.Header.Set("X-Token", t.APIKey)
	return nil
}
func (s *WebhookClient) securityTokenHeader(ctx context.Context, operationName OperationName, req *http.Request) error {
	t, err := s.sec.TokenHeader(ctx, operationName)
	if err != nil {
		return errors.Wrap(err, "security source \"TokenHeader\"")
	}
	req.Header.Set("X-Token", t.APIKey)
	return nil
}
